"""services.observability 包初始化：链路追踪与性能可观测性接口。"""
from infra.observability.audit import audit
from infra.observability.observability import (  # noqa: F401
    trace_block,
    clear_traces,
    get_recent_traces,
    get_recent_traces_scoped,
    get_recent_spans,
    get_recent_spans_scoped,
    get_trace_timeline,
    get_slowest_spans,
    get_slowest_spans_scoped,
    get_latency_summary,
    get_latency_summary_scoped,
    add_trace,
    add_span,
    set_current_trace_id,
    reset_current_trace_id,
    get_current_trace_id,
    set_current_span_id,
    reset_current_span_id,
    get_current_span_id,
)

__all__ = [
    "add_span",
    "add_trace",
    "audit",
    "clear_traces",
    "get_current_span_id",
    "get_current_trace_id",
    "get_latency_summary",
    "get_latency_summary_scoped",
    "get_recent_spans",
    "get_recent_spans_scoped",
    "get_recent_traces",
    "get_recent_traces_scoped",
    "get_slowest_spans",
    "get_slowest_spans_scoped",
    "get_trace_timeline",
    "reset_current_span_id",
    "reset_current_trace_id",
    "set_current_span_id",
    "set_current_trace_id",
    "trace_block",
]
