from db.crud.doctor import (
    _utcnow,
    _WECHAT_ID_RE,
    _is_wechat_identifier,
    _infer_channel,
    _resolve_doctor_id,
    _ensure_doctor_exists,
    get_doctor_by_id,
    get_doctor_wechat_user_id,
    get_doctor_mini_openid,
    get_doctor_by_mini_openid,
    link_mini_openid,
    get_doctor_context,
    upsert_doctor_context,
    add_doctor_knowledge_item,
    list_doctor_knowledge_items,
    get_doctor_session_state,
    upsert_doctor_session_state,
    get_doctor_notify_preference,
    upsert_doctor_notify_preference,
    get_recent_conversation_turns,
    append_conversation_turns,
    clear_conversation_turns,
    purge_conversation_turns_before,
    append_chat_archive,
)
from db.crud.system import (
    get_system_prompt,
    upsert_system_prompt,
    list_system_prompt_versions,
    rollback_system_prompt,
)
from db.crud.patient import (
    get_patient_for_doctor,
    create_patient,
    find_patient_by_name,
    find_patients_by_exact_name,
    delete_patient_for_doctor,
    get_all_patients,
    create_label,
    get_labels_for_doctor,
    update_label,
    delete_label,
    assign_label,
    remove_label,
    get_patient_labels,
    update_patient_demographics,
)
from db.crud.records import (
    save_record,
    get_records_for_patient,
    get_all_records_for_doctor,
    save_neuro_case,
    get_neuro_cases_for_doctor,
    save_record_version,
    get_record_versions,
    update_latest_record_for_patient,
    _env_flag_true,
    _CN_DIGITS,
    _parse_cn_or_int,
    _extract_follow_up_days,
    _patient_name,
    _ensure_auto_follow_up_task,
)
from db.crud.tasks import (
    create_task,
    list_tasks,
    update_task_status,
    get_task_by_id,
    update_task_due_at,
    get_due_tasks,
    mark_task_notified,
)
from db.crud.pending import (
    create_pending_record,
    get_pending_record,
    get_stale_pending_records,
    confirm_pending_record,
    abandon_pending_record,
    expire_stale_pending_records,
    purge_old_pending_records,
    purge_old_pending_messages,
    create_pending_message,
    mark_pending_message,
    list_stale_pending_messages,
)
from db.crud.scores import (
    save_specialty_scores,
    get_scores_for_record,
)
from db.crud.specialty import (
    save_cvd_context,
    get_cvd_context_for_patient,
)
from db.crud.runtime import (
    get_runtime_cursor,
    upsert_runtime_cursor,
    get_runtime_token,
    upsert_runtime_token,
    get_runtime_config,
    upsert_runtime_config,
    try_acquire_scheduler_lease,
    release_scheduler_lease,
)
from db.crud.retention import (
    archive_old_audit_logs,
    prune_record_versions,
    cleanup_chat_archive,
)

__all__ = [
    # doctor
    "_utcnow",
    "_WECHAT_ID_RE",
    "_is_wechat_identifier",
    "_infer_channel",
    "_resolve_doctor_id",
    "_ensure_doctor_exists",
    "get_doctor_by_id",
    "get_doctor_wechat_user_id",
    "get_doctor_mini_openid",
    "get_doctor_by_mini_openid",
    "link_mini_openid",
    "get_doctor_context",
    "upsert_doctor_context",
    "add_doctor_knowledge_item",
    "list_doctor_knowledge_items",
    "get_doctor_session_state",
    "upsert_doctor_session_state",
    "get_doctor_notify_preference",
    "upsert_doctor_notify_preference",
    "get_recent_conversation_turns",
    "append_conversation_turns",
    "clear_conversation_turns",
    "purge_conversation_turns_before",
    "append_chat_archive",
    # system
    "get_system_prompt",
    "upsert_system_prompt",
    "list_system_prompt_versions",
    "rollback_system_prompt",
    # patient
    "get_patient_for_doctor",
    "create_patient",
    "find_patient_by_name",
    "find_patients_by_exact_name",
    "delete_patient_for_doctor",
    "get_all_patients",
    "create_label",
    "get_labels_for_doctor",
    "update_label",
    "delete_label",
    "assign_label",
    "remove_label",
    "get_patient_labels",
    "update_patient_demographics",
    # records
    "save_record",
    "get_records_for_patient",
    "get_all_records_for_doctor",
    "save_neuro_case",
    "get_neuro_cases_for_doctor",
    "save_record_version",
    "get_record_versions",
    "update_latest_record_for_patient",
    "_env_flag_true",
    "_CN_DIGITS",
    "_parse_cn_or_int",
    "_extract_follow_up_days",
    "_patient_name",
    "_ensure_auto_follow_up_task",
    # tasks
    "create_task",
    "list_tasks",
    "update_task_status",
    "get_task_by_id",
    "update_task_due_at",
    "get_due_tasks",
    "mark_task_notified",
    # pending
    "create_pending_record",
    "get_pending_record",
    "get_stale_pending_records",
    "confirm_pending_record",
    "abandon_pending_record",
    "expire_stale_pending_records",
    "purge_old_pending_records",
    "purge_old_pending_messages",
    "create_pending_message",
    "mark_pending_message",
    "list_stale_pending_messages",
    # scores
    "save_specialty_scores",
    "get_scores_for_record",
    # specialty context
    "save_cvd_context",
    "get_cvd_context_for_patient",
    # runtime
    "get_runtime_cursor",
    "upsert_runtime_cursor",
    "get_runtime_token",
    "upsert_runtime_token",
    "get_runtime_config",
    "upsert_runtime_config",
    "try_acquire_scheduler_lease",
    "release_scheduler_lease",
    # retention
    "archive_old_audit_logs",
    "prune_record_versions",
    "cleanup_chat_archive",
]
