/**
 * Workflow 13 — Persona pending review (AI discoveries)
 *
 * Mirrors docs/qa/workflows/13-persona-pending.md.
 *
 * Because pending items are generated by the backend AI pipeline, the spec
 * intercepts the GET endpoint and returns canned pending items to keep tests
 * deterministic without requiring a live LLM.
 */
import { test, expect } from "./fixtures/doctor-auth";

const PENDING_URL = "**/api/manage/persona/pending?doctor_id=*";

/** Factory: build a fake pending item */
function fakePendingItem(overrides: Record<string, unknown> = {}) {
  return {
    id: `pending_${Math.random().toString(36).slice(2, 8)}`,
    field: "reply_style",
    proposed_rule: "口语化回复，像微信聊天",
    evidence_summary: "在最近5次回复中，医生都使用了口语化的表达方式",
    confidence: "high",
    ...overrides,
  };
}

test.describe("Workflow 13 — Persona pending review", () => {
  test("1. Empty state shows placeholder", async ({ doctorPage }) => {
    // Intercept pending API to return empty list
    await doctorPage.route(PENDING_URL, (route) =>
      route.fulfill({
        status: 200,
        contentType: "application/json",
        body: JSON.stringify({ items: [] }),
      }),
    );

    await doctorPage.goto("/doctor/settings/persona/pending");

    // step 1.1 — page header
    await expect(doctorPage.getByText("AI发现")).toBeVisible();
    // step 1.2 — empty state
    await expect(doctorPage.getByText("暂无待确认的发现")).toBeVisible();
  });

  test("2. Items render with field labels and confidence", async ({ doctorPage }) => {
    const items = [
      fakePendingItem({
        id: "p1",
        field: "reply_style",
        proposed_rule: "简洁直接，不绕弯",
        evidence_summary: "近期回复平均长度较短",
        confidence: "high",
      }),
      fakePendingItem({
        id: "p2",
        field: "closing",
        proposed_rule: "祝早日康复",
        evidence_summary: "70%的回复以祝福语结尾",
        confidence: "medium",
      }),
    ];

    await doctorPage.route(PENDING_URL, (route) =>
      route.fulfill({
        status: 200,
        contentType: "application/json",
        body: JSON.stringify({ items }),
      }),
    );

    await doctorPage.goto("/doctor/settings/persona/pending");

    // step 2.1 — both items render
    await expect(doctorPage.getByText("简洁直接，不绕弯")).toBeVisible();
    await expect(doctorPage.getByText("祝早日康复")).toBeVisible();

    // step 2.2 — field label chips
    await expect(doctorPage.getByText("回复风格")).toBeVisible();
    await expect(doctorPage.getByText("常用结尾语")).toBeVisible();

    // step 2.2 — confidence labels
    await expect(doctorPage.getByText("确信")).toBeVisible();
    await expect(doctorPage.getByText("可能")).toBeVisible();

    // step 2.2 — evidence summaries
    await expect(doctorPage.getByText("近期回复平均长度较短")).toBeVisible();
    await expect(doctorPage.getByText("70%的回复以祝福语结尾")).toBeVisible();

    // step 2.3 — action buttons per card
    const confirmButtons = doctorPage.getByRole("button", { name: "确认" });
    const ignoreButtons = doctorPage.getByRole("button", { name: "忽略" });
    await expect(confirmButtons).toHaveCount(2);
    await expect(ignoreButtons).toHaveCount(2);
  });

  test("3. Accept removes item from list", async ({ doctorPage, doctor }) => {
    const items = [
      fakePendingItem({ id: "p1", proposed_rule: "口语化回复" }),
      fakePendingItem({ id: "p2", field: "avoid", proposed_rule: "不要用医学缩写" }),
    ];

    let currentItems = [...items];

    await doctorPage.route(PENDING_URL, (route) => {
      if (route.request().method() === "GET") {
        return route.fulfill({
          status: 200,
          contentType: "application/json",
          body: JSON.stringify({ items: currentItems }),
        });
      }
      return route.continue();
    });

    // Intercept accept endpoint for p1
    await doctorPage.route("**/api/manage/persona/pending/p1/accept*", (route) => {
      currentItems = currentItems.filter((i) => i.id !== "p1");
      return route.fulfill({ status: 200, contentType: "application/json", body: "{}" });
    });

    await doctorPage.goto("/doctor/settings/persona/pending");

    // Both items visible
    await expect(doctorPage.getByText("口语化回复")).toBeVisible();
    await expect(doctorPage.getByText("不要用医学缩写")).toBeVisible();

    // step 3.1 — tap confirm on first item
    const confirmButtons = doctorPage.getByRole("button", { name: "确认" });
    await confirmButtons.first().click();

    // step 3.2 — first item disappears, second remains
    await expect(doctorPage.getByText("口语化回复")).toBeHidden();
    await expect(doctorPage.getByText("不要用医学缩写")).toBeVisible();
  });

  test("4. Reject removes item and shows empty state when last", async ({ doctorPage }) => {
    const items = [
      fakePendingItem({ id: "p1", proposed_rule: "结尾加鼓励语" }),
    ];

    let currentItems = [...items];

    await doctorPage.route(PENDING_URL, (route) => {
      if (route.request().method() === "GET") {
        return route.fulfill({
          status: 200,
          contentType: "application/json",
          body: JSON.stringify({ items: currentItems }),
        });
      }
      return route.continue();
    });

    await doctorPage.route("**/api/manage/persona/pending/p1/reject*", (route) => {
      currentItems = [];
      return route.fulfill({ status: 200, contentType: "application/json", body: "{}" });
    });

    await doctorPage.goto("/doctor/settings/persona/pending");
    await expect(doctorPage.getByText("结尾加鼓励语")).toBeVisible();

    // step 4.2 — tap ignore
    await doctorPage.getByRole("button", { name: "忽略" }).click();

    // step 4.3 — item gone, empty state shown
    await expect(doctorPage.getByText("结尾加鼓励语")).toBeHidden();
    await expect(doctorPage.getByText("暂无待确认的发现")).toBeVisible();
  });
});
